apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    path: appsets
    repoURL: https://github.com/kostis-codefresh/many-appsets-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
